Implemented local override config file

diff --git a/shmig b/shmig
--- a/shmig
+++ b/shmig
@@ -656,6 +656,18 @@ then
   die "Configuration file '$CONFIG' doesn't exist"
 fi
 
+# Include local config, if available (e.g., shmig.local.conf
+LOCAL_CONFIG="${CONFIG%.*}.local.${CONFIG##*.}"
+if [ -e "$LOCAL_CONFIG" ]; then
+  # any error in configuration file should cause failure
+  # to avoid potential database corruption
+  trap 'die "Local configuration failed"' ERR
+  source "$LOCAL_CONFIG"
+  # reset handler
+  trap - ERR
+fi
+
+
 [[ $ASK_PASSWORD -eq 1 ]] && read -s -p "Password: " _PASSWORD
 
 # options from command line have higher priority than configuration
